# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YuemojKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YuemojKit
  pod 'Masonry', '~>1.1.0'
  pod 'PinYin4Objc', '~> 1.1.1'
#  pod 'YuemojKit', :path => '../'
  pod 'YuemojKit', '~>1.0.5'
end

#post_install do |installer|
#  installer.generated_projects.each do |project|
#    project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#        config.build_settings["ENABLE_BITCODE"] = "NO"
#      end
#    end
#  end
#end
